### ISSUE TITLE
Workshop lights are unreliable

### ISSUE THREAD

**Issue by jmacarthur** [HACManchester/Space#16]
Tubes are L 70W/835

**Comment by thinkl33t** [comment]
We've tried changing out the bulbs, the issue is with the fittings themselves.  They use a ballast instead of a regular starter, so we cant change it out without paying ~ £80 per fitting.

The lights can be turned on fairly reliably by flicking the light switch on, waiting five seconds, then flicking it on and off a few times until the lights turn on.

**Comment by thinkl33t** [comment]
bjdooks has replaced the ballasts in these lights and they are now coming on first time every time.
